### ISSUE TITLE
Regression in Upgrade header handling

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/http-parser#217]
See https://github.com/iojs/io.js/issues/627 and https://github.com/iojs/io.js/pull/628 for background.

In a nutshell, 2.4.1 doesn't like uncommon Upgrade header formats.  The regression test in https://github.com/iojs/io.js/pull/628 is a good example.

/cc @indutny

**Comment by mscdex** [comment]
"Uncommon" here means "invalid" since both `Connection: upgrade` and `Upgrade: ...` are required according to [RFC 7230](https://tools.ietf.org/html/rfc7230#page-59) (second paragraph). Unless we're wanting to support broken clients.... but are there real cases of that out in the wild where clients *only* send `Upgrade`?

On a semi-related note, `Upgrade` headers must also be ignored if received from an HTTP 1.0 client. I'm guessing this should be handled at the parser layer?

**Comment by indutny** [comment]
@mscdex all of your comment is correct, except that I have introduced an unintentional behavior change. This means that there could be some bug that I have overlooked.

**Comment by indutny** [comment]
Nah, I see now where this behavior was introduced 091ebb87 . @bnoordhuis on a second thought I think that @mscdex is right about it as the change was quite intentional.

@bnoordhuis Why do we want to support this?

**Comment by indutny** [comment]
Not a regression.
